# Generated by Django 3.2 on 2022-05-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='item_quantity',
            field=models.IntegerField(),
        ),
    ]
