# Generated by Django 3.2 on 2022-05-13 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinalsApp', '0005_auto_20220512_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='expiration_date',
        ),
    ]
