# Generated by Django 3.2 on 2022-05-13 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinalsApp', '0009_alter_order_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='expiration_date',
        ),
    ]
