# Generated by Django 3.2 on 2022-05-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalsApp', '0013_alter_order_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Java 101', 'Java 101'), ('Python 101', 'Python 101'), ('Biology 101', 'Biology 101'), ('English 101', 'English 101'), ('Cloud Computing 101', 'Cloud Computing 101')], max_length=25, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='item_description',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='item_description',
            field=models.ManyToManyField(to='FinalsApp.Products'),
        ),
    ]
