# Generated by Django 3.2 on 2022-05-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalsApp', '0014_auto_20220513_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='item_description',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='item_description',
            field=models.CharField(choices=[('Java 101', 'Java 101'), ('Python 101', 'Python 101'), ('Biology 101', 'Biology 101'), ('English 101', 'English 101'), ('Cloud Computing 101', 'Cloud Computing 101')], default='Java 101', max_length=25),
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
