# Generated by Django 3.2 on 2022-05-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalsApp', '0015_auto_20220513_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
